FROM node:22-alpine

WORKDIR /app/frontend

COPY frontend/package*.json ./
RUN npm ci

EXPOSE 5173

ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
