ALTER TABLE media ADD COLUMN IF NOT EXISTS medium_url TEXT NOT NULL DEFAULT '';
ALTER TABLE media ADD COLUMN IF NOT EXISTS large_url TEXT NOT NULL DEFAULT '';
ALTER TABLE media ADD COLUMN IF NOT EXISTS blur_hash TEXT NOT NULL DEFAULT '';
