apiVersion: v1
kind: ConfigMap
metadata:
  name: relax-hub-config
  labels:
    app.kubernetes.io/name: relax-hub
data:
  BANI_ENVIRONMENT: staging
  BANI_BASE_URL: https://relax-hub.ru
  BANI_FRONTEND_URL: https://relax-hub.ru

  BANI_SERVER_HOST: 0.0.0.0
  BANI_SERVER_PORT: "8080"

  BANI_LOGGER_LEVEL: info
  BANI_LOGGER_FORMAT: json
  BANI_CORS_ALLOWED_ORIGINS: https://relax-hub.ru

  BANI_DATABASE_MAX_CONNS: "10"
  BANI_DATABASE_MIN_CONNS: "1"
  BANI_DATABASE_MAX_CONN_LIFETIME: 1h

  BANI_REDIS_DB: "0"

  BANI_STORAGE_ENDPOINT: relax-hub-minio:9000
  BANI_STORAGE_PUBLIC_BASE_URL: https://relax-hub.ru
  BANI_STORAGE_BUCKET: relax-hub-media
  BANI_STORAGE_REGION: us-east-1
  BANI_STORAGE_USE_SSL: "false"

  BANI_PAYMENT_RETURN_URL: https://relax-hub.ru/payment/callback
  BANI_OAUTH_VK_REDIRECT_URL: https://relax-hub.ru/api/v1/auth/oauth/vk/callback
  BANI_OAUTH_YANDEX_REDIRECT_URL: https://relax-hub.ru/api/v1/auth/oauth/yandex/callback
  BANI_OAUTH_GOOGLE_REDIRECT_URL: https://relax-hub.ru/api/v1/auth/oauth/google/callback

  BANI_TELEGRAM_MODE: polling
  BANI_CRON_ENABLED: "true"
  BANI_CRON_TIMEZONE: Europe/Moscow
