apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: relax-hub
resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - redis.yaml
  - minio.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
  - backup/cronjob.yaml
images:
  - name: relax-hub-api
    newName: ghcr.io/rekurt/relax-hub-api
    newTag: "latest"
  - name: relax-hub-frontend
    newName: ghcr.io/rekurt/relax-hub-frontend
    newTag: "latest"
