package domain

import "errors"

var (
	ErrNotFound               = errors.New("not found")
	ErrAlreadyExists          = errors.New("already exists")
	ErrInvalidInput           = errors.New("invalid input")
	ErrUnauthorized           = errors.New("unauthorized")
	ErrForbidden              = errors.New("forbidden")
	ErrSlotUnavailable        = errors.New("time slot is unavailable")
	ErrBookingCancelLate      = errors.New("too late to cancel booking")
	ErrUserBlocked            = errors.New("user is blocked")
	ErrBathhouseNotActive     = errors.New("bathhouse is not active")
	ErrBathhouseHasBookings   = errors.New("cannot delete bathhouse with active bookings")
	ErrReviewAlreadyResponded     = errors.New("review already has owner response")
	ErrSocialAccountAlreadyLinked = errors.New("social account already linked")
	ErrSocialAccountNotFound      = errors.New("social account not found")
	ErrOAuthExchangeFailed        = errors.New("oauth code exchange failed")
	ErrSubscriptionNotFound       = errors.New("subscription not found")
	ErrSubscriptionAlreadyActive  = errors.New("subscription already active")
	ErrPromotionBudgetExhausted   = errors.New("promotion budget exhausted")
	ErrInsufficientPoints         = errors.New("insufficient loyalty points")
	ErrPromoNotFound              = errors.New("promo code not found")
	ErrPromoExpired               = errors.New("promo code expired")
	ErrPromoMaxUses               = errors.New("promo code usage limit exceeded")
	ErrPromoMinAmount             = errors.New("promo code minimum amount not met")
	ErrPromoInvalid               = errors.New("promo code is invalid")
	ErrComplaintNotFound          = errors.New("complaint not found")
	ErrAlreadyReported            = errors.New("already reported")
	ErrSelfReferral               = errors.New("cannot refer yourself")
	ErrAlreadyReferred            = errors.New("user already referred")
	ErrInsufficientReferralBalance = errors.New("insufficient referral balance")

	ErrCertificateNotFound            = errors.New("gift certificate not found")
	ErrCertificateExpired             = errors.New("gift certificate expired")
	ErrCertificateInsufficientBalance = errors.New("gift certificate insufficient balance")

	ErrPhotoNotFound = errors.New("photo not found")

	ErrMediaNotFound     = errors.New("media not found")
	ErrMediaFileTooLarge = errors.New("media file too large")
	ErrMediaInvalidType  = errors.New("media invalid file type")
	ErrMediaLimitReached = errors.New("media upload limit reached")
)
